---
title: "HILIC_Knowns_Comp"
author: "Kaden Coulter"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

```{r}
knowns = read.csv("HILIC_KNOWNS.csv") 
preds = read.csv("40631942.csv") 
ambig = read.csv("40703382.csv")

knowns = knowns[knowns$smiles != "" & !is.na(knowns$smiles), ] 
ambig = ambig[ambig$SMILES != "" & !is.na(ambig$SMILES), ] 

if (length(knowns$smiles) != length(preds$SMILES)) 
  { message("Length mismatch between predictions and inputs in Known HILIC... Halting.") 
  stopifnot(length(knowns$smiles) != length(preds$SMILES))} 

knowns = knowns %>% select(-RT) 
knowns$rt = preds$True.RT 
knowns$preds = preds$Predicted.RT 
message("Predictions paired back to input. Continuing...")
```

```{r}


# NOT A CHOSEN FIG
# base$distance <- with(base,
#     ifelse(preds < min * 60, preds - min * 60,
#     ifelse(preds > max * 60, preds - max * 60,
#     0)))
#base$x_ <- seq_len(nrow(base))
# ggplot(base, aes(x = x_, y = distance)) +
#   geom_point(alpha = 0.5) +
#   geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
#   theme_bw() +
#   xlab("METABOLITE") +
#   ylab("PREDICTED DISTANCE FROM RT RANGE") + 
#   scale_x_continuous(
#     breaks = c(0, max(base$x_)),
#     labels = c("0", as.character(max(base$x_)))) +
#   theme(
#     axis.title = element_text(size = 13),
#     axis.text = element_text(size = 12))
message("Generating Figure: Predicted vs Observed RT...")

line_df <- data.frame(x = c(0, 1300), y = c(0, 1300), Type = "Perfect Prediction")

legend_order <- factor(c("Known", "Unknown Mean", "Perfect Prediction"), 
                       levels = c("Known", "Unknown Mean", "Perfect Prediction"))

plot = ggplot() +
  geom_point(data = knowns, aes(x = rt, y = preds, color = factor("Known", levels = levels(legend_order))), alpha = 0.7) +
  geom_point(data = ambig, aes(x = True.RT, y = Predicted.RT, color = factor("Unknown Mean", levels = levels(legend_order))), alpha = 0.3) +
  geom_line(data = line_df, aes(x = x, y = y, linetype = Type, color = Type), linetype = "dashed", size = 1.2) +
  theme_bw() +
  xlab("OBSERVED RT (s)") +
  ylab("PREDICTED RT (s)") +
  theme(
    axis.title = element_text(size = 14),
    axis.text  = element_text(size = 12)) +
  scale_color_manual(
    name = "HILIC Dataset Source",
    values = c("Known" = "red", "Unknown Mean" = "cornflowerblue", "Perfect Prediction" = "black")) +
  scale_x_continuous(limits = c(0, 1300), breaks = c(0, 325, 650, 975, 1300), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 1300), breaks = c(0, 325, 650, 975, 1300), expand = c(0, 0))

plot

MAE_known <- abs(knowns$rt - knowns$preds)
MAE_ambig <- abs(ambig$Predicted.RT - ambig$True.RT)
test <- wilcox.test(MAE_known, MAE_ambig, exact = FALSE)
#test

ggsave(filename = "Pred_vs_Obs.svg", plot = plot, height = 6, width = 8)

```
